[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Partición con más espacio para flash (4MB con OTA)
board_build.partitions = min_spiffs.csv

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    links2004/WebSockets @ ^2.4.0
    h2zero/NimBLE-Arduino @ ^1.4.0

monitor_speed = 115200

; Optimización de tamaño
build_flags =
    -Os
    -DCONFIG_BT_NIMBLE_ENABLED=1